name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Adicionar dependência do Firebase Admin SDK
dependencies:
  path: ^1.9.0
  firebase_admin: ^0.2.0 # Use a versão mais recente disponível

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6